### ISSUE TITLE
happi edit command not working for boolean variables

### ISSUE THREAD

**Issue by Mbosum** [pcdshub/happi#187]
## Expected Behavior
Edit command should edit the field properly

## Current Behavior
This seems to be broken for booleans

## Steps to Reproduce (for bugs)
Run `happi edit xpp_pol_wp lightpath=False`
xpp_pol_wp entry has `lightpath=True`

## Context
Trying to add laser motor to xpp's beamline

## Your Environment
pcds-3.4.1 on xcs-control

**Comment by ZLLentz** [comment]
Did a quick readthrough of the code, at first look it seems like `happi` is simply casting the string "False" to a boolean... which is `True`:
```
In [2]: bool("False")
Out[2]: True
```
Because boolean fields are implemented like so:
https://github.com/pcdshub/pcdsdevices/blob/c5d9806d11a680ea1985f651ce2ecfa0df3b299f/pcdsdevices/happi/containers.py#L25

And the code simple calls the `enforce` function as a preprocessor on the user input.

This suggests that you can do the following as a workaround:
`happi edit xpp_pol_wp lightpath=`

Which should put an empty string into the database- a `False` value. (I have not tried this yet, but that's the theory).

To resolve this issue we probably need to rework the value enforcement for boolean fields a bit, or carve out a special case for them in the edit cli.

**Comment by klauer** [comment]
Users seem to be running into these pretty consistently: https://github.com/pcdshub/happi/issues/165#issuecomment-695141777

Should probably make a point of reviewing all keys to see if this list is exhaustive.
